### ISSUE TITLE
Major order tracker is not displaying correctly.

### ISSUE THREAD

**Issue by The-Eye-of-Ar3s** [vonbeardy/hd2galaxy-issues#59]
The current major order requires the following 4 planets to be under super earth control by the time it expires.
- Aesir Pass
- Vernen Wells
- Heeth
- Angel's Venture

The website currently displays all 4 planets to be under super earth control, while this is not true ingame. As of right now (UTC: 7:00 17.05.24), Aesir Pass and Heeth are at 64% and 43% defense and notably **not** marked as under super earth control by the game.
![image](https://github.com/vonbeardy/hd2galaxy-issues/assets/77468397/d032af4a-ea8d-4ab1-bbe5-cc699cdecc01)
The website, however, displays them as successfully held.
![image](https://github.com/vonbeardy/hd2galaxy-issues/assets/77468397/6f78e703-b281-4937-b993-7a41d8842d7e)

Notably, the correct percentages are displayed on the map
![image](https://github.com/vonbeardy/hd2galaxy-issues/assets/77468397/c976fdd2-a36c-4876-9bb6-6670c4774805)
and in the "galaxy stats" under "Event Progress"
![image](https://github.com/vonbeardy/hd2galaxy-issues/assets/77468397/e669068f-cf51-4652-8e87-0fc138f256ba)

I suspect this has something to do with the fact that the website still counts these planets as 100% liberated in _some_ regard.
![image](https://github.com/vonbeardy/hd2galaxy-issues/assets/77468397/71595970-a075-4faa-8b31-c0be651c3f0c)

**Comment by vonbeardy** [comment]
@The-Eye-of-Ar3s, thanks for the post. In short, the Major Order is correct. Let me go into more details of why. 

Firstly, the official API shows that a liberated planet is a planet under Super Earth control. A defense mission does not take that liberation away unless the defense operation fails at which point it goes to the attacking faction and will no longer be under Super Earth control. This is why the Major Orders show as completed on the site and it currently puts the Helldivers in a winning situation. This is supported by the image of the in-game Major Order, you can see the green box (success) for the main order, "Designated planets must be under Super Earth Control..." is present, so even the game believes we have control (which we do). Keyword here for the Major Order is "control".

Second, the choice of how to represent the planets in the Major Order is a bit subjective. AH has decided to show the planets under a defense mission as not complete although they are 100% liberate (under Super Earth control) and just defending their ground. To me this is misleading since they show the overall Major Order as completed, at the moment, but not the two planets in a defense mission.

With that said, I do need to put up percentages of progress and current states in the Major Order so it is a bit more clear but time has been really limited for me as of late but I will track an issue for that.
